_PATH_DATA = "Datasets/DB_proyecto_SA.txt"
_MODELO = "model.joblib"
_MODELO_NET = "modelmlp.h5"
_BUCKET = "files-training"
_BUCKET_MODELS = "modelslearning"
_TABLE_MODELS = "models"
_TABLE_INGEST = "data2"